using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RSCG_DBContext;

[Generator]
public sealed partial class DbContextExistsGenerator : IIncrementalGenerator
{
    internal const string AttributeFullName = "RSCG_DBContext.GenerateDbContextExistsAttribute";

    internal static readonly DiagnosticDescriptor MustInheritDbContext = new(
        id: "RSCGDB001",
        title: "Attribute requires a DbContext",
        messageFormat: "GenerateDbContextExistsAttribute can only be applied to classes that inherit from Microsoft.EntityFrameworkCore.DbContext. '{0}' is not a DbContext.",
        category: "RSCG_DBContext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MustBePartial = new(
        id: "RSCGDB002",
        title: "DbContext must be partial",
        messageFormat: "The DbContext class '{0}' must be declared partial to generate Exists_* members",
        category: "RSCG_DBContext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string AttributeSource = """
// <auto-generated/>
namespace RSCG_DBContext
{
    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal class GenerateDbContextExistsAttribute : global::System.Attribute
    {
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource("GenerateDbContextExistsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, cancellationToken) => BuildGenerationResult(ctx, cancellationToken));

        context.RegisterSourceOutput(candidates, static (ctx, result) =>
        {
            foreach (var diagnostic in result.Diagnostics)
            {
                ctx.ReportDiagnostic(diagnostic);
            }

            if (result.Model is null)
            {
                return;
            }

            ctx.AddSource(
                $"{result.Model.SourceHintName}.DbContextExists.g.cs",
                SourceText.From(Render(result.Model), Encoding.UTF8));
        });
    }

    private static GenerationResult BuildGenerationResult(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var classSymbol = (INamedTypeSymbol)context.TargetSymbol;
        var classSyntax = (TypeDeclarationSyntax)context.TargetNode;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var dbContextSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Microsoft.EntityFrameworkCore.DbContext");
        var dbSetSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Microsoft.EntityFrameworkCore.DbSet`1");
        var targetTypeDeclaration = GetTypeDeclaration(classSymbol, cancellationToken);
        if (dbContextSymbol is null || !InheritsFrom(classSymbol, dbContextSymbol))
        {
            diagnostics.Add(Diagnostic.Create(MustInheritDbContext, classSyntax.Identifier.GetLocation(), classSymbol.ToDisplayString()));
            return new GenerationResult(null, diagnostics.ToImmutable());
        }

        if (!IsPartial(classSymbol, cancellationToken))
        {
            diagnostics.Add(Diagnostic.Create(MustBePartial, classSyntax.Identifier.GetLocation(), classSymbol.ToDisplayString()));
            return new GenerationResult(null, diagnostics.ToImmutable());
        }

        var dbSetPropertyNames = dbSetSymbol is null
            ? ImmutableArray<string>.Empty
            : GetDbSetPropertyNames(classSymbol, dbSetSymbol);

        return new GenerationResult(
            new GenerationModel(
                classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString(),
                CreateTypeShape(classSymbol, targetTypeDeclaration),
                GetContainingTypes(classSymbol, cancellationToken),
                dbSetPropertyNames),
            diagnostics.ToImmutable());
    }

    internal static string Render(GenerationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");

        if (!string.IsNullOrWhiteSpace(model.NamespaceName))
        {
            builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
            builder.AppendLine("{");
        }

        foreach (var containingType in model.ContainingTypes)
        {
            builder.Append("partial ").Append(containingType.DeclarationKeyword).Append(' ').Append(containingType.Name).AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("partial ").Append(model.TargetType.DeclarationKeyword).Append(' ').Append(model.TargetType.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var propertyName in model.DbSetPropertyNames)
        {
            builder.Append("    public bool Exists_").Append(propertyName).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("        try");
            builder.AppendLine("        {");
            builder.Append("            _ = global::System.Linq.Queryable.LongCount(this.").Append(propertyName).AppendLine(");");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine("        catch");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }
        builder.Append("    public IEnumerable<string> Problem_DBSets()");
        builder.AppendLine("    {");
        foreach (var propertyName in model.DbSetPropertyNames)
        {
            builder.AppendLine("        if(!Exists_" + propertyName + "()) yield return \"" + propertyName + "\";");
        }
        builder.AppendLine("    }");


        builder.Append("    public bool Exists_AllDBSets()");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        foreach (var propertyName in model.DbSetPropertyNames)
        {
            builder.AppendLine("        if(!Exists_" + propertyName + "()) return false;");
        }
        builder.AppendLine("        }");
        builder.AppendLine("        catch");
        builder.AppendLine("        {");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine("return true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        
        builder.AppendLine("}");

        for (var index = model.ContainingTypes.Length - 1; index >= 0; index--)
        {
            builder.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(model.NamespaceName))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static bool InheritsFrom(INamedTypeSymbol typeSymbol, INamedTypeSymbol expectedBaseType)
    {
        for (var current = typeSymbol; current is not null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, expectedBaseType))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsDbSet(ITypeSymbol typeSymbol, INamedTypeSymbol dbSetSymbol)
    {
        return typeSymbol is INamedTypeSymbol namedType
               && SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, dbSetSymbol);
    }

    private static ImmutableArray<string> GetDbSetPropertyNames(INamedTypeSymbol classSymbol, INamedTypeSymbol dbSetSymbol)
    {
        var propertyNames = new HashSet<string>(StringComparer.Ordinal);

        for (var currentType = classSymbol; currentType is not null; currentType = currentType.BaseType)
        {
            foreach (var property in currentType.GetMembers().OfType<IPropertySymbol>())
            {
                if (property.DeclaredAccessibility == Accessibility.Public
                    && !property.IsStatic
                    && IsDbSet(property.Type, dbSetSymbol))
                {
                    propertyNames.Add(property.Name);
                }
            }
        }

        return propertyNames
            .OrderBy(static propertyName => propertyName, StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private static bool IsPartial(INamedTypeSymbol classSymbol, CancellationToken cancellationToken)
    {
        var declarations = classSymbol.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax(cancellationToken))
            .OfType<TypeDeclarationSyntax>()
            .ToImmutableArray();

        return declarations.Length > 0
               && declarations.All(static declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static ImmutableArray<TypeShapeModel> GetContainingTypes(INamedTypeSymbol classSymbol, CancellationToken cancellationToken)
    {
        var builder = ImmutableArray.CreateBuilder<TypeShapeModel>();

        for (var containingType = classSymbol.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            builder.Add(CreateTypeShape(containingType, GetTypeDeclaration(containingType, cancellationToken)));
        }

        builder.Reverse();
        return builder.ToImmutable();
    }

    private static TypeDeclarationSyntax GetTypeDeclaration(INamedTypeSymbol symbol, CancellationToken cancellationToken)
    {
        return symbol.DeclaringSyntaxReferences
                   .Select(reference => reference.GetSyntax(cancellationToken))
                   .OfType<TypeDeclarationSyntax>()
                   .FirstOrDefault()
               ?? throw new InvalidOperationException($"Unable to find a declaration for '{symbol.ToDisplayString()}'.");
    }

    private static TypeShapeModel CreateTypeShape(INamedTypeSymbol symbol, TypeDeclarationSyntax declaration)
    {
        return new TypeShapeModel(GetTypeName(symbol), GetDeclarationKeyword(declaration), symbol.MetadataName);
    }

    private static string GetDeclarationKeyword(TypeDeclarationSyntax declaration)
    {
        return declaration switch
        {
            RecordDeclarationSyntax recordDeclaration when recordDeclaration.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) => "record struct",
            RecordDeclarationSyntax recordDeclaration when recordDeclaration.ClassOrStructKeyword.IsKind(SyntaxKind.ClassKeyword) => "record class",
            RecordDeclarationSyntax => "record",
            ClassDeclarationSyntax => "class",
            StructDeclarationSyntax => "struct",
            InterfaceDeclarationSyntax => "interface",
            _ => "class"
        };
    }

    private static string GetTypeName(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
        {
            return symbol.Name;
        }

        return $"{symbol.Name}<{string.Join(", ", symbol.TypeParameters.Select(static typeParameter => typeParameter.Name))}>";
    }
}
