using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RSCG_DBContext;

[Generator]
public sealed class DbContextExistsGenerator : IIncrementalGenerator
{
    internal const string AttributeFullName = "RSCG_DBContext.GenerateDbContextExistsAttribute";

    internal static readonly DiagnosticDescriptor MustInheritDbContext = new(
        id: "RSCGDB001",
        title: "Attribute requires a DbContext",
        messageFormat: "GenerateDbContextExistsAttribute can only be applied to classes that inherit from Microsoft.EntityFrameworkCore.DbContext. '{0}' is not a DbContext.",
        category: "RSCG_DBContext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MustBePartial = new(
        id: "RSCGDB002",
        title: "DbContext must be partial",
        messageFormat: "The DbContext class '{0}' must be declared partial to generate Exists_* members",
        category: "RSCG_DBContext",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string AttributeSource = """
// <auto-generated/>
namespace RSCG_DBContext
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateDbContextExistsAttribute : global::System.Attribute
    {
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GenerateDbContextExistsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, cancellationToken) => BuildGenerationResult(ctx, cancellationToken));

        context.RegisterSourceOutput(candidates, static (ctx, result) =>
        {
            foreach (var diagnostic in result.Diagnostics)
            {
                ctx.ReportDiagnostic(diagnostic);
            }

            if (result.Model is null)
            {
                return;
            }

            ctx.AddSource(
                $"{result.Model.SourceHintName}.DbContextExists.g.cs",
                SourceText.From(Render(result.Model), Encoding.UTF8));
        });
    }

    private static GenerationResult BuildGenerationResult(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        var classSymbol = (INamedTypeSymbol)context.TargetSymbol;
        var classSyntax = (ClassDeclarationSyntax)context.TargetNode;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var dbContextSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Microsoft.EntityFrameworkCore.DbContext");
        var dbSetSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Microsoft.EntityFrameworkCore.DbSet`1");
        if (dbContextSymbol is null || !InheritsFrom(classSymbol, dbContextSymbol))
        {
            diagnostics.Add(Diagnostic.Create(MustInheritDbContext, classSyntax.Identifier.GetLocation(), classSymbol.ToDisplayString()));
            return new GenerationResult(null, diagnostics.ToImmutable());
        }

        if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            diagnostics.Add(Diagnostic.Create(MustBePartial, classSyntax.Identifier.GetLocation(), classSymbol.ToDisplayString()));
            return new GenerationResult(null, diagnostics.ToImmutable());
        }

        var dbSetPropertyNames = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => property.DeclaredAccessibility == Accessibility.Public && !property.IsStatic)
            .Where(property => dbSetSymbol is not null && IsDbSet(property.Type, dbSetSymbol))
            .Select(static property => property.Name)
            .OrderBy(static name => name, StringComparer.Ordinal)
            .ToImmutableArray();

        return new GenerationResult(
            new GenerationModel(
                classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString(),
                GetTypeName(classSymbol),
                GetContainingTypeNames(classSymbol),
                dbSetPropertyNames),
            diagnostics.ToImmutable());
    }

    internal static string Render(GenerationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");

        if (!string.IsNullOrWhiteSpace(model.NamespaceName))
        {
            builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
            builder.AppendLine("{");
        }

        foreach (var containingTypeName in model.ContainingTypeNames)
        {
            builder.Append("partial class ").Append(containingTypeName).AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("partial class ").Append(model.ClassName).AppendLine();
        builder.AppendLine("{");

        foreach (var propertyName in model.DbSetPropertyNames)
        {
            builder.Append("    public bool Exists_").Append(propertyName).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("        try");
            builder.AppendLine("        {");
            builder.Append("            _ = global::System.Linq.Queryable.LongCount(this.").Append(propertyName).AppendLine(");");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine("        catch");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");

        for (var index = model.ContainingTypeNames.Length - 1; index >= 0; index--)
        {
            builder.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(model.NamespaceName))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static bool InheritsFrom(INamedTypeSymbol typeSymbol, INamedTypeSymbol expectedBaseType)
    {
        for (var current = typeSymbol; current is not null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, expectedBaseType))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsDbSet(ITypeSymbol typeSymbol, INamedTypeSymbol dbSetSymbol)
    {
        return typeSymbol is INamedTypeSymbol namedType
               && SymbolEqualityComparer.Default.Equals(namedType.OriginalDefinition, dbSetSymbol);
    }

    private static ImmutableArray<string> GetContainingTypeNames(INamedTypeSymbol classSymbol)
    {
        var builder = ImmutableArray.CreateBuilder<string>();

        for (var containingType = classSymbol.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            builder.Add(GetTypeName(containingType));
        }

        builder.Reverse();
        return builder.ToImmutable();
    }

    private static string GetTypeName(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
        {
            return symbol.Name;
        }

        return $"{symbol.Name}<{string.Join(", ", symbol.TypeParameters.Select(static typeParameter => typeParameter.Name))}>";
    }

    internal sealed class GenerationModel
    {
        public GenerationModel(
            string? namespaceName,
            string className,
            ImmutableArray<string> containingTypeNames,
            ImmutableArray<string> dbSetPropertyNames)
        {
            NamespaceName = namespaceName;
            ClassName = className;
            ContainingTypeNames = containingTypeNames;
            DbSetPropertyNames = dbSetPropertyNames;
        }

        public string? NamespaceName { get; }

        public string ClassName { get; }

        public ImmutableArray<string> ContainingTypeNames { get; }

        public ImmutableArray<string> DbSetPropertyNames { get; }

        public string SourceHintName =>
            ContainingTypeNames.Length == 0
                ? ClassName
                : $"{string.Join(".", ContainingTypeNames)}.{ClassName}";
    }

    private sealed class GenerationResult
    {
        public GenerationResult(GenerationModel? model, ImmutableArray<Diagnostic> diagnostics)
        {
            Model = model;
            Diagnostics = diagnostics;
        }

        public GenerationModel? Model { get; }

        public ImmutableArray<Diagnostic> Diagnostics { get; }
    }
}
